### ISSUE TITLE
why the switch from firebase to hasura and nhost

### ISSUE THREAD

**Issue by nzaero** [usagizmo/webapp-template#768]
hi,
I would like to know what was the arguments to replace firebase to hasura and nhost. 
I just know firebase, so I am curious what was the motivation to remove it.
tks

**Comment by usagizmo** [comment]
Thanks for your comment.
I wanted to use GraphQL (especially Hasura) instead of Firestore.
If I were to use GraphQL with Firebase, I would have to use Functions to synchronize with another DB, and I didn't want that to be complicated.

On the backend, I need to think about DB (GraphQL)/Authentication/Storage, and I chose nhost because it currently has all of that in one service.
