### ISSUE TITLE
[Discussion] Supabase/BAAS vs Postgres + Drizzle + Lucia/Auth.js

### ISSUE THREAD

**Issue by ESchouten** [usagizmo/webapp-template#793]
First of all, my compliments to you for this repo. It's the cleanest, best maintained and fully featured without bloat monorepo template I know. 

I created this issue because I would like to start a discussion on whether or not Supabase or other BAAS solutions are the best option to include in this/a template versus using an ORM in combination with an external authentication provider.

Views could be opinionated due to not having enough experience with Supabase.

Some pros of using your own backend vs Supabase: 
- ORMs like Drizzle export Zod types for the tables defined. This can be used for automatic validation on the client side as well as on the server side. Types and validation rules are automatically updated with the database definition.
- All logic is defined in typescript in the project. No SQL functions/triggers in migration files.
- Every action goes through Sveltekit first with actions/endpoints. Just submit the form instead of e.g. the Userstore -> updateUser function
- The authentication provider implementation (including database tables?) with e.g. Lucia could be extracted to a package in the monorepo which the different apps could use.

**Comment by usagizmo** [comment]
Thank you very much for your kind words! I am very pleased to hear that.
Also, thank you for sharing your valuable opinions.

First of all, I am not very knowledgeable about backend development, but I consider using BaaS to reduce the burden of smoothly implementing backend functionalities (such as “user authentication,” “DB,” and “file storage”) in web service development.

### Drizzle

I learned about Drizzle for the first time, but it seems to be compatible with Supabase, so it might be worth trying.
I will refer to the following links:

* https://supabase.com/docs/guides/database/connecting-to-postgres#connecting-with-drizzle
* https://orm.drizzle.team/learn/tutorials/drizzle-with-supabase

### Lucia

The main reason I want to use BaaS is that I can use it conveniently as an integrated solution.
I understand the flexibility of Lucia, but at present, I plan to adopt Supabase.
However, I will continue to investigate Lucia and consider it in the future.

* https://github.com/lucia-auth/lucia/discussions/325

## Customizability of the Template

Since the Supabase client is used as a simple client (`supabaseClient.ts`), it is relatively easy to switch to other services.
Please feel free to customize this template as needed.

<details>
<summary>Note: Current Method of Linking DB Tables and Type Information</summary>

I am developing using Supabase with the following procedure:

1. Start the development server (`apps/backend`) `pnpm start #=> supabase start`
   Access `localhost:54323` to access the management screen (Supabase Studio?).
2. Create and edit table permissions using the GUI in Supabase Studio.
3. After updating the table, output the migration file with `supabase pull`.
4. Run `pnpm generate` in [apps/web] to output the type information to `apps/web/src/lib/$generated/supabase-types.ts`.

With the above procedure, table changes, migrations, and output of TypeScript type information can be done easily by using the GUI and executing commands.
</details>
